dist: xenial
language: python
python: 3.8-dev
install:
- gem install asciidoctor coderay
- pip3 install -r requirements.txt
script:
- make html update-code test
git:
  submodules: false
before_install:
- sudo apt-get install -y tree python-pygments
- sed -i s_git@github.com:_https://github.com/_ .gitmodules
- git submodule update --init --recursive
